### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Question\Question::getAutocompleterCallback()

### ISSUE THREAD

**Issue by ragusa87** [liip/RMT#153]
Running RMT release in an interactive mode crash as soon as a question is asked.

The trace is as below:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Question\Question::getAutocompleterCallback() in /home/vagrant/.composer/vendor/symfony/console/Helper/QuestionHelper.php:119
Stack trace:
#0 /home/vagrant/.composer/vendor/symfony/console/Helper/QuestionHelper.php(85): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#1 /home/vagrant/.composer/vendor/symfony/console/Helper/QuestionHelper.php(430): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#2 /home/vagrant/.composer/vendor/symfony/console/Helper/QuestionHelper.php(88): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#3 /home/vagrant/.composer/vendor/liip/rmt/src/Liip/RMT/Output/Output.php(132): Symfony\Component\Console\Helper\QuestionHelpe in /home/vagrant/.composer/vendor/symfony/console/Helper/QuestionHelper.php on line 119
```

Composer versions:
```
composer/ca-bundle          1.2.4   Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla ...
liip/rmt                    1.5.2   Release Management Tool: a handy tool to help releasing new version of your software
psr/container               1.0.0   Common Container Interface (PHP FIG PSR-11)
sensiolabs/security-checker v5.0.3  A security checker for your composer.lock
symfony/console             v4.3.5  Symfony Console Component
symfony/polyfill-ctype      v1.12.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring   v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73      v1.12.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process             v4.3.5  Symfony Process Component
symfony/service-contracts   v1.1.7  Generic abstractions related to writing services
symfony/yaml                v4.3.5  Symfony Yaml Component
vierbergenlars/php-semver   3.0.2   The Semantic Versioner for PHP

```
PHP Version
```
PHP 7.2.22-1+0~20190902.26+debian8~1.gbpd64eb7 (cli) (built: Sep  2 2019 14:27:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.22-1+0~20190902.26+debian8~1.gbpd64eb7, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by ragusa87** [comment]
Ping @Jonathanm10

**Comment by boyet007** [comment]
any solution about this problem?
